// reactFront/src/pages/DoctorDetails.tsx
import { useParams } from "react-router-dom";
import Icon from "../components/Icon/Icon";
import styles from "./DoctorDetails.module.css";
import { useDispatch, useSelector } from "react-redux";
import { AppDispatch, RootState } from "../redux/store";
import { useEffect, useState } from "react";
import {
  Doctor,
  GetDoctorResult,
  UpdateDoctorResult,
  getDoctor,
  updateDoctor,
} from "../redux/DoctorReducer";
import notFound from "../assets/image-not-found.jpg";
import { deleteFile, uploadFile } from "../redux/FileReducer";
import { GetTokenFromLocalStorage, setToken } from "../redux/UserReducer";

export default function DoctorDetails() {
  const { doctorId } = useParams();

  const authToken = useSelector((state: RootState) => state.user.token);

  useEffect(() => {
    const localStorageValue = GetTokenFromLocalStorage();

    if (localStorageValue) {
      dispatch(setToken(localStorageValue));
    }
  }, []);

  const dispatch = useDispatch<AppDispatch>();

  const doctor = useSelector(
    (state: RootState) => state.doctor.data as GetDoctorResult
  );

  const [toggleMode, setToggleMode] = useState<boolean>(false);

  const [name, setName] = useState("");
  const [department, setDepartment] = useState("");
  const [description, setDescription] = useState("");

  const [selectedFile, setSelectedFile] = useState(null);

  const handleToggleMode = () => {
    setToggleMode(!toggleMode);
  };

  const handleDoctorUpdate = async (updatedDoctor: Doctor) => {
    try {
      var updateDoctorResult = await dispatch(
        updateDoctor({ doctor: updatedDoctor, token: authToken })
      );

      var updateDoctorBody = updateDoctorResult.payload as UpdateDoctorResult;

      if (updateDoctorBody.IsSuccess === true && selectedFile) {
        const fileResult = await dispatch(
          uploadFile({
            file: selectedFile,
            relKey: doctor.MyResult.DOCTORID,
            relTable: "DOCTORTABLE",
            relField: "DoctorImage",
          })
        );

        console.log(fileResult);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const deleteImage = async (id: number) => {
    var result = await dispatch(deleteFile({ id, token: authToken }));
    console.log(result);
  };

  useEffect(() => {
    const fetchData = async () => {
      try {
        await dispatch(getDoctor(parseInt(doctorId)));
      } catch (error) {
        console.error("Error fetching doctor:", error);
      }
    };

    fetchData();
  }, []);

  const doctorForm = new Doctor();
  doctorForm.DOCTORID = +doctorId;
  doctorForm.DEPARTMENT = department;
  doctorForm.NAME = name;
  doctorForm.DESCRIPTION = description;
  doctorForm.TWITTERLINK = doctor?.MyResult.TWITTERLINK;
  doctorForm.FACEBOOKLINK = doctor?.MyResult.FACEBOOKLINK;
  doctorForm.INSTAGRAMLINK = doctor?.MyResult.INSTAGRAMLINK;

  useEffect(() => {
    setName(doctor?.MyResult.NAME || "");
    setDescription(doctor?.MyResult.DESCRIPTION || "");
    setDepartment(doctor?.MyResult.DEPARTMENT || "");
  }, [doctor]);

  if (doctor) {
    if (!toggleMode) {
      return (
        <div className={`${styles.doctorDetails} container`}>
          <div className={styles.image}>
            {doctor.MyResult.Files ? (
              <img src={doctor.MyResult.Files[0].URL} alt="" />
            ) : (
              <img src={notFound} alt="" />
            )}
          </div>
          <div className={styles.details}>
            <h1>{doctor.MyResult.NAME}</h1>
            <h3>{doctor.MyResult.DEPARTMENT}</h3>
            <p>{doctor.MyResult.DESCRIPTION}</p>
            <div className={styles.icons}>
              <Icon
                iconContainerSize={"iconContainerMd"}
                cursorPointer={"pointerCursor"}
                icon={"fab fa-facebook-f"}
                iconSize={"iconMd"}
              />
              <Icon
                iconContainerSize={"iconContainerMd"}
                cursorPointer={"pointerCursor"}
                icon={"fab fa-twitter"}
                iconSize={"iconMd"}
              />
              <Icon
                iconContainerSize={"iconContainerMd"}
                cursorPointer={"pointerCursor"}
                icon={"fab fa-instagram"}
                iconSize={"iconMd"}
              />
              <button className={styles.toggleBtn} onClick={handleToggleMode}>
                Edit
              </button>
            </div>
          </div>
        </div>
      );
    } else {
      return (
        <div className={`${styles.doctorDetails} container`}>
          <div className={styles.image}>
            {doctor?.MyResult?.Files ? (
              <img src={doctor.MyResult.Files[0].URL} alt="" />
            ) : (
              <img src={notFound} alt="" />
            )}
            <div>
              <button
                className={styles.deleteBtn}
                onClick={() => deleteImage(doctor.MyResult.Files[0].FILEID)}
              >
                X
              </button>
            </div>
          </div>
          <div className={styles.details}>
            <input
              type="text"
              name=""
              id=""
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <input
              type="text"
              name=""
              id=""
              value={department}
              onChange={(e) => setDepartment(e.target.value)}
            />
            <input
              type="text"
              name=""
              id=""
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
            <input
              type="file"
              name=""
              id=""
              onChange={(e) => setSelectedFile(e.target.files[0])}
            />
            <div className={styles.icons}>
              <Icon
                iconContainerSize={"iconContainerMd"}
                cursorPointer={"pointerCursor"}
                icon={"fab fa-facebook-f"}
                iconSize={"iconMd"}
              />
              <Icon
                iconContainerSize={"iconContainerMd"}
                cursorPointer={"pointerCursor"}
                icon={"fab fa-twitter"}
                iconSize={"iconMd"}
              />
              <Icon
                iconContainerSize={"iconContainerMd"}
                cursorPointer={"pointerCursor"}
                icon={"fab fa-instagram"}
                iconSize={"iconMd"}
              />
              <button
                className={styles.toggleBtn}
                onClick={() => handleDoctorUpdate(doctorForm)}
              >
                Update
              </button>
            </div>
          </div>
        </div>
      );
    }
  } else {
    return null;
  }
}

// frontApp/src/pages/doctor-details/doctor-details.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { Doctor, DoctorService } from '../../services/doctor.service';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { IconComponent } from '../../components/icon/icon.component';
import { InputComponent } from '../../components/input/input.component';
import { FormsModule } from '@angular/forms';
import { FileService } from '../../services/file.service';

@Component({
  selector: 'app-doctor-details',
  standalone: true,
  imports: [IconComponent, InputComponent, FormsModule],
  templateUrl: './doctor-details.component.html',
  styleUrl: './doctor-details.component.css',
})
export class DoctorDetailsComponent implements OnInit {
  doctor: Doctor;
  id: number;
  name: string;
  department: string;
  description: string;
  toggleEditMode: boolean = false;
  files: File[];

  private doctorService = inject(DoctorService);
  private route = inject(ActivatedRoute);
  private fileService = inject(FileService);

  ngOnInit(): void {
    this.route.paramMap.subscribe((params: ParamMap) => {
      this.id = +params.get('id');
    });

    this.GetDoctor(this.id);
  }

  GetDoctor(id: number) {
    this.doctorService.GetDoctor(id).subscribe({
      next: (result) => {
        console.log(result), (this.doctor = result.MyResult);
      },
      error: (err) => console.error(err),
    });
  }

  ToggleEditMode() {
    this.toggleEditMode = !this.toggleEditMode;
    this.name = this.doctor.NAME;
    this.department = this.doctor.DEPARTMENT;
    this.description = this.doctor.DESCRIPTION;
  }

  onChange(event: any) {
    const files: File[] = event.target.files;
    this.files = files;
  }

  UpdateDoctor() {
    const doc = new Doctor();
    doc.NAME = this.name;
    doc.DEPARTMENT = this.department;
    doc.DESCRIPTION = this.description;
    doc.DOCTORID = this.doctor.DOCTORID;
    doc.FACEBOOKLINK = this.doctor.FACEBOOKLINK;
    doc.TWITTERLINK = this.doctor.TWITTERLINK;
    doc.INSTAGRAMLINK = this.doctor.INSTAGRAMLINK;

    this.doctorService.UpdateDoctor(doc).subscribe({
      next: (doctorResult) => {
        console.log(doctorResult);
        if (doctorResult.IsSuccess === true && this.files) {
          this.fileService
            .UploadFile(
              this.files,
              doctorResult.MyResult.DOCTORID,
              'DoctorImage',
              'DOCTORTABLE'
            )
            .subscribe({
              next: (fileResult) => {
                console.log(fileResult);
              },
              error: (err) => console.error(err),
            });
        }
        this.GetDoctor(this.id), (this.toggleEditMode = false);
      },
      error: (err) => console.error(err),
    });
  }

  DeleteFile(fileId: number) {
    this.fileService.DeleteFile(fileId).subscribe({
      next: (result) => {
        console.log(result);
        if (result.IsSuccess === true) {
          this.GetDoctor(this.id);
        }
      },
      error: (err) => console.error(err),
    });
  }
}

@if(doctor){ @if(!toggleEditMode){
<div class="doctor-details container">
  <div class="image">
    @if(doctor.Files){
    <img [src]="doctor.Files[0].URL" alt="" srcset="" />
    }@else{
    <img src="../../assets/image-not-found.jpg" alt="" srcset="" />
    }
  </div>
  <div class="details">
    <h1>{{ doctor.NAME }}</h1>
    <h3>{{ doctor.DEPARTMENT }}</h3>
    <p>{{ doctor.DESCRIPTION }}</p>
    <div class="icons">
      <app-icon
        [icon]="'fab fa-facebook-f'"
        [iconContainerSize]="'icon-container-md'"
        [iconSize]="'icon-md'"
        [cursorPointer]="'pointer-cursor'"
      ></app-icon>
      <app-icon
        [icon]="'fab fa-twitter'"
        [iconContainerSize]="'icon-container-md'"
        [iconSize]="'icon-md'"
        [cursorPointer]="'pointer-cursor'"
      ></app-icon>
      <app-icon
        [icon]="'fab fa-instagram'"
        [iconContainerSize]="'icon-container-md'"
        [iconSize]="'icon-md'"
        [cursorPointer]="'pointer-cursor'"
      ></app-icon>
      <button class="toggle-btn" (click)="ToggleEditMode()">Edit</button>
      <!-- <app-icon
        [icon]="'fa-solid fa-pen-to-square'"
        [iconContainerSize]="'icon-container-md'"
        [iconSize]="'icon-md'"
        [cursorPointer]="'pointer-cursor'"
      ></app-icon> -->
    </div>
  </div>
</div>
}@else{
<div class="doctor-details container">
  <div class="image">
    @if(doctor.Files){
    <img [src]="doctor.Files[0].URL" alt="" srcset="" />
    }@else{
    <img src="../../assets/image-not-found.jpg" alt="" srcset="" />
    }
    <div>
      <button class="delete-btn" (click)="DeleteFile(doctor.Files[0].FILEID)">
        X
      </button>
    </div>
  </div>
  <div class="details">
    <app-input
      [type]="'text'"
      [placeholder]="'name'"
      [(ngModel)]="name"
    ></app-input>
    <app-input
      [type]="'text'"
      [placeholder]="'department'"
      [(ngModel)]="department"
    ></app-input>
    <app-input
      [type]="'text'"
      [placeholder]="'description'"
      [(ngModel)]="description"
    ></app-input>
    <app-input
      [type]="'file'"
      [placeholder]="'add file'"
      (change)="onChange($event)"
    ></app-input>
    <button class="update-btn" (click)="UpdateDoctor()">Update</button>
  </div>
</div>
} } @if(!toggleEditMode){
<!-- <button (click)="ToggleEditMode()">Edit</button> -->
}@else{
<!-- <button (click)="UpdateDoctor()">Update</button> -->
}
