// reactFront/src/components/Testimonial/Testimonial.tsx
import { useState } from "react";
import { Testimonial } from "../../redux/TestimonialReducer";
import styles from "./Testimonial.module.css";

interface TestimonialProps {
  testimonials: Testimonial[];
}

export default function TestimonialComponent({
  testimonials,
}: TestimonialProps) {
  const initialIndex = Math.floor(testimonials.length / 2);

  const [selectedIndex, setSelectedIndex] = useState(initialIndex);
  const [animationDirection, setAnimationDirection] = useState("");

  const onPrevClick = (currentIndex: number) => {
    if (currentIndex === 0) {
      setSelectedIndex(testimonials.length - 1);
      setAnimationDirection(styles.moveLeft);
    } else {
      setSelectedIndex(currentIndex - 1);
      setAnimationDirection(styles.moveLeft);
    }
  };

  const onNextClick = (currentIndex: number) => {
    if (currentIndex === testimonials.length - 1) {
      setSelectedIndex(0);
      setAnimationDirection(styles.moveRight);
    } else {
      setSelectedIndex(currentIndex + 1);
      setAnimationDirection(styles.moveRight);
    }
  };

  return (
    <section className={`${styles.testimonialSection}`}>
      <div className={`${styles.testimonialContainer} container`}>
        <p className="section-title">Testimonial</p>
        <h1 className={styles.testimonialHeading}>What Our Patients Say</h1>
        <div className={styles.flexContainer}>
          {testimonials.map((testimonial, index) => (
            <div
              className={`${styles.testimonialCard} ${selectedIndex === index ? styles.active : ""} ${animationDirection}`}
              key={index}
            >
              <div className={styles.upperSection}>
                <i
                  className={`fa-solid fa-arrow-left ${styles.iconLeft} ${styles.icon}`}
                  onClick={() => onPrevClick(index)}
                ></i>
                <div className={styles.patientImage}>
                  <img src={testimonial.File.URL} alt="" />
                </div>
                <i
                  className={`fa-solid fa-arrow-right ${styles.iconRight} ${styles.icon}`}
                  onClick={() => onNextClick(index)}
                ></i>
              </div>
              <div className={styles.textSection}>
                <div className={styles.text}>
                  <p>{testimonial.DESCRIPTION}</p>
                  <p className={styles.name}>{testimonial.USERNAME}</p>
                  <p className={styles.profession}>{testimonial.PROFESSION}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// frontApp/src/components/testimonial/testimonial.component.ts
import { NgClass } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Testimonial } from '../../services/testimonial.service';

@Component({
  selector: 'app-testimonial',
  standalone: true,
  imports: [NgClass],
  templateUrl: './testimonial.component.html',
  styleUrl: './testimonial.component.css',
})
export class TestimonialComponent {
  @Input() testimonials: Testimonial[] = [];

  selectedIndex = Math.floor(this.testimonials.length / 2);

  animationDirection = '';

  selectImage(index: number): void {
    this.selectedIndex = index;
  }

  onPrevClick(): void {
    if (this.selectedIndex === 0) {
      this.selectedIndex = this.testimonials.length - 1;
      this.animationDirection = 'left';
    } else {
      this.selectedIndex--;
      this.animationDirection = 'left';
    }
  }

  onNextClick(): void {
    if (this.selectedIndex === this.testimonials.length - 1) {
      this.selectedIndex = 0;
      this.animationDirection = 'right';
    } else {
      this.selectedIndex++;
      this.animationDirection = 'right';
    }
  }
}

<!-- <section class="testimonial-section">
  <div class="testimonial-container container">
    <p class="section-title">Testimonial</p>
    <h1 class="testimonial-heading">What Our Patients Say</h1>
    <div class="testimonial-card">
      <div class="test">
         @for(t of testimonials; track t.image){
        <div class="upper-section">
          <i class="fa-solid fa-arrow-left icon-left icon"></i>
          <div class="patient-image">
            <img [src]="t.image" alt="" />
          </div>
          <i class="fa-solid fa-arrow-right icon-right icon"></i>
        </div>

        <div class="text">
          <p>
            {{ t.text }}
          </p>
          <p class="name">{{ t.name }}</p>
          <p class="profession">{{ t.profession }}</p>
        </div>
        }

        <div class="upper-section">
          <i class="fa-solid fa-arrow-left icon-left icon"></i>
          <div class="patient-image">
            <img src="../../assets/testimonial-1.jpg" alt="" />
          </div>
          <i class="fa-solid fa-arrow-right icon-right icon"></i>
        </div>

        <div class="text">
          <p>text</p>
          <p class="name">name</p>
          <p class="profession">profession</p>
        </div>
      </div>
    </div>
  </div>
</section> -->

<!-- <section class="testimonial-section">
  <div class="testimonial-container container">
    <p class="section-title">Testimonial</p>
    <h1 class="testimonial-heading">What Our Patients Say</h1>
    <div class="testimonial-card">
      <div class="upper-section">
        <i class="fa-solid fa-arrow-left icon-left icon"></i>
        <div class="patient-image">
          <img src="../../assets/testimonial-1.jpg" alt="" />
        </div>
        <i class="fa-solid fa-arrow-right icon-right icon"></i>
      </div>
      <div class="text-section">
        <div class="text">
          <p>text</p>
          <p class="name">name</p>
          <p class="profession">profession</p>
        </div>
      </div>
    </div>
  </div>
</section> -->

<section class="testimonial-section">
  <div class="testimonial-container container">
    <p class="section-title">Testimonial</p>
    <h1 class="testimonial-heading">What Our Patients Say</h1>
    <div class="flex-container">
      @for(t of testimonials; track t.TESTIMONIALID; let i = $index){
      <div
        class="testimonial-card"
        [ngClass]="{
          active: selectedIndex === i,
          'move-left': animationDirection === 'left',
          'move-right': animationDirection === 'right'
        }"
      >
        <div class="upper-section">
          <i
            class="fa-solid fa-arrow-left icon-left icon"
            (click)="onPrevClick()"
          ></i>
          <div class="patient-image">
            <img [src]="t.File.URL" alt="" />
          </div>
          <i
            class="fa-solid fa-arrow-right icon-right icon"
            (click)="onNextClick()"
          ></i>
        </div>
        <div class="text-section">
          <div class="text">
            <p>{{ t.DESCRIPTION }}</p>
            <p class="name">{{ t.USERNAME }}</p>
            <p class="profession">{{ t.PROFESSION }}</p>
          </div>
        </div>
      </div>
      }
    </div>
  </div>
</section>
