// frontApp/src/components/appointment/appointment.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Appointment } from '../../services/appointment.service';
import { InputComponent } from '../input/input.component';

@Component({
  selector: 'app-appointment',
  standalone: true,
  imports: [FormsModule, InputComponent],
  templateUrl: './appointment.component.html',
  styleUrl: './appointment.component.css',
})
export class AppointmentComponent {
  @Output() appointmentObject = new EventEmitter<Appointment>();
  @Input() isFormLoading: boolean;

  name: string;
  email: string;
  mobile: string;
  doctor: string;
  description: string;
  date: Date;
  time: string;
  inputType: string;

  SendAppointmentObject() {
    const appointment: Appointment = {
      APPOINTMENTID: 0,
      NAME: this.name,
      EMAIL: this.email,
      DOCTOR: this.doctor,
      MOBILE: this.mobile,
      DESCRIPTION: this.description,
      DATE: this.date,
      TIME: this.time,
    };
    this.appointmentObject.emit(appointment);
  }
}

<section class="appointment-section">
  <div class="appointment-container container">
    <div class="appointment-info">
      <p class="section-title">Appointment</p>
      <p class="appointment-heading">
        Make An Appointment To Visit Our Doctors
      </p>
      <p class="appointment-text">
        Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam
        amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit
        clita duo justo magna dolore erat amet
      </p>
      <div class="call-us">
        <div class="phone-icon"><i class="fa fa-phone-alt"></i></div>
        <div class="call-us-info">
          <p class="call-us-text">Call Us Now</p>
          <p class="phone-number">+012 345 6789</p>
        </div>
      </div>

      <div class="mail-us">
        <div class="phone-icon"><i class="fa fa-envelope-open"></i></div>
        <div class="call-us-info">
          <p class="call-us-text">Mail Us Now</p>
          <p class="phone-number">info&#64;example.com</p>
        </div>
      </div>
    </div>
    <div class="appointment-form">
      <app-input
        [type]="'text'"
        [placeholder]="'name'"
        [(ngModel)]="name"
        [inputName]="'name'"
      ></app-input>
      <app-input
        [type]="'email'"
        [placeholder]="'Your Email'"
        [(ngModel)]="email"
      ></app-input>
      <app-input
        type="'tel'"
        placeholder="Your Mobile"
        [(ngModel)]="mobile"
      ></app-input>
      <app-input
        type="text"
        placeholder="Chose Doctor"
        [(ngModel)]="doctor"
      ></app-input>
      <app-input
        placeholder="Chose Date"
        type="date"
        [(ngModel)]="date"
      ></app-input>
      <app-input
        placeholder="Chose Time"
        type="time"
        [(ngModel)]="time"
      ></app-input>
      <textarea
        cols="30"
        rows="10"
        placeholder="Describe Your Problem"
        [(ngModel)]="description"
      ></textarea>
      <button
        [disabled]="isFormLoading"
        class="book-appointment-btn"
        (click)="SendAppointmentObject()"
      >
        Book Appointment
      </button>
    </div>
  </div>
</section>

<!-- <input
        type="text"
        placeholder="Your Name"
        [(ngModel)]="name"
        [disabled]="isFormLoading"
      />
      <input
        type="text"
        placeholder="Your Email"
        [(ngModel)]="email"
        [disabled]="isFormLoading"
      />
      <input
        type="text"
        placeholder="Your Mobile"
        [(ngModel)]="mobile"
        [disabled]="isFormLoading"
      />
      <input
        type="text"
        placeholder="Chose Doctor"
        [(ngModel)]="doctor"
        [disabled]="isFormLoading"
      />
      <input
        placeholder="Chose Date"
        type="text"
        onfocus="(this.type='date')"
        onblur="(this.type='text')"
        [(ngModel)]="date"
        [disabled]="isFormLoading"
      />
      <input
        placeholder="Chose Time"
        type="text"
        onfocus="(this.type='time')"
        onblur="(this.type='text')"
        [(ngModel)]="time"
        [disabled]="isFormLoading"
      />
      <textarea
        cols="30"
        rows="10"
        placeholder="Describe Your Problem"
        [(ngModel)]="description"
        [disabled]="isFormLoading"
      ></textarea>
      <button
        [disabled]="isFormLoading"
        class="book-appointment-btn"
        (click)="SendAppointmentObject()"
      >
        Book Appointment
      </button> -->

// reactFront/src/components/Appointment/Appointment.tsx
import { useState } from "react";
import Input from "../Input/Input";
import styles from "./Appointment.module.css";
import { Appointment } from "../../redux/AppointmentReducer";

interface AppointmentFormValues {
  onFormSubmit: any;
}

export default function AppointmentComponent({
  onFormSubmit,
}: AppointmentFormValues) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [mobile, setMobile] = useState("");
  const [doctor, setDoctor] = useState("");
  const [date, setDate] = useState(null);
  const [time, setTime] = useState("");
  const [description, setDescription] = useState("");

  const handleNameChange = (value: string) => {
    setName(value);
  };
  const handleEmailChange = (value: string) => {
    setEmail(value);
  };
  const handleMobileChange = (value: string) => {
    setMobile(value);
  };
  const handleDoctorChange = (value: string) => {
    setDoctor(value);
  };
  const handleDateChange = (value: string) => {
    setDate(value);
  };
  const handleTimeChange = (value: string) => {
    setTime(value);
  };

  const appointment = new Appointment();
  appointment.NAME = name;
  appointment.EMAIL = email;
  appointment.MOBILE = mobile;
  appointment.DOCTOR = doctor;
  appointment.DATE = date;
  appointment.TIME = time;
  appointment.DESCRIPTION = description;

  const handleFormSubmit = () => {
    onFormSubmit(appointment);
  };

  return (
    <section className={styles.appointmentSection}>
      <div className={`${styles.appointmentContainer} container`}>
        <div className={styles.appointmentInfo}>
          <p className="section-title">Appointment</p>
          <p className={styles.appointmentHeading}>
            Make An Appointment To Visit Our Doctors
          </p>
          <p className={styles.appointmentText}>
            Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu
            diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet
            lorem sit clita duo justo magna dolore erat amet
          </p>
          <div className={styles.callUs}>
            <div className={styles.phoneIcon}>
              <i className="fa fa-phone-alt"></i>
            </div>
            <div className={styles.callUsInfo}>
              <p className={styles.callUsText}>Call Us Now</p>
              <p className={styles.phoneNumber}>+012 345 6789</p>
            </div>
          </div>

          <div className={styles.mailUs}>
            <div className={styles.mailIcon}>
              <i className="fa fa-envelope-open"></i>
            </div>
            <div className={styles.callUsInfo}>
              <p className={styles.callUsText}>Mail Us Now</p>
              <p className={styles.email}>info&#64;example.com</p>
            </div>
          </div>
        </div>
        <div className={styles.appointmentForm}>
          <Input
            inputType={"text"}
            placeholder={"Name"}
            onInputChange={handleNameChange}
            name={"NAME"}
            handleFileInputChange={null}
          />
          <Input
            inputType={"email"}
            placeholder={"Your Email"}
            onInputChange={handleEmailChange}
            name={"EMAIL"}
            handleFileInputChange={null}
          />
          <Input
            inputType={"text"}
            placeholder={"Your Mobile"}
            onInputChange={handleMobileChange}
            name={"MOBILE"}
            handleFileInputChange={null}
          />
          <Input
            inputType={"text"}
            placeholder={"Choose Doctor"}
            onInputChange={handleDoctorChange}
            name={"DOCTOR"}
            handleFileInputChange={null}
          />
          <Input
            inputType={"date"}
            placeholder={"Choose Date"}
            onInputChange={handleDateChange}
            name={"DATE"}
            handleFileInputChange={null}
          />
          <Input
            inputType={"time"}
            placeholder={"Choose Time"}
            onInputChange={handleTimeChange}
            name={"TIME"}
            handleFileInputChange={null}
          />
          <textarea
            cols={30}
            rows={10}
            placeholder="Describe Your Problem"
            name="DESCRIPTION"
            onChange={(e) => setDescription(e.target.value)}
          ></textarea>

          <button
            className={styles.bookBppointmentBtn}
            onClick={handleFormSubmit}
          >
            Book Appointment
          </button>
        </div>
      </div>
    </section>
  );
}
