// frontApp/src/pages/appointments/appointments.component.ts
import { Component, OnInit, inject } from '@angular/core';
import {
  Appointment,
  AppointmentService,
} from '../../services/appointment.service';

@Component({
  selector: 'app-appointments',
  standalone: true,
  imports: [],
  templateUrl: './appointments.component.html',
  styleUrl: './appointments.component.css',
})
export class AppointmentsComponent implements OnInit {
  appointmentService = inject(AppointmentService);
  ngOnInit(): void {
    this.GetAppointments();
  }

  appointments: Appointment[];

  GetAppointments() {
    this.appointmentService.GetAppointments().subscribe({
      next: (result) => {
        this.appointments = result.MyResult;
        console.log(result);
      },
      error: (err) => console.error(err),
    });
  }
}

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Name</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Doctor</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    @for(appointment of appointments; track appointment.APPOINTMENTID){
    <tr>
      <td>{{ appointment.DATE }}</td>
      <td>{{ appointment.TIME }}</td>
      <td>{{ appointment.NAME }}</td>
      <td>{{ appointment.MOBILE }}</td>
      <td>{{ appointment.EMAIL }}</td>
      <td>{{ appointment.DOCTOR }}</td>
      <td>{{ appointment.DESCRIPTION }}</td>
    </tr>
    }
  </tbody>
</table>

// reactFront/src/pages/Appointments.tsx
import { useDispatch } from "react-redux";
import { AppDispatch } from "../redux/store";
import { useEffect, useState } from "react";
import {
  GetAppointmentsResult,
  getAppointments,
} from "../redux/AppointmentReducer";
import styles from "./Appointments.module.css";

export default function Appointments() {
  const dispatch = useDispatch<AppDispatch>();

  const [appointments, setAppointments] = useState<GetAppointmentsResult>(null);

  useEffect(() => {
    const abortController = new AbortController();

    const fetchData = async () => {
      try {
        var result = await dispatch(getAppointments());

        var resultBody = result.payload as GetAppointmentsResult;

        setAppointments(resultBody);
      } catch (error) {
        console.error(error);
      }
    };

    fetchData();

    return () => {
      abortController.abort();
    };
  }, []);

  return (
    <table className={styles.table}>
      <thead>
        <tr>
          <th className={styles.th}>Date</th>
          <th className={styles.th}>Time</th>
          <th className={styles.th}>Name</th>
          <th className={styles.th}>Mobile</th>
          <th className={styles.th}>Email</th>
          <th className={styles.th}>Doctor</th>
          <th className={styles.th}>Description</th>
        </tr>
      </thead>
      <tbody>
        {appointments
          ? appointments.MyResult?.map((appointment) => (
              <tr key={appointment.APPOINTMENTID}>
                <td className={styles.td}>{appointment.DATE.toString()}</td>
                <td className={styles.td}>{appointment.TIME}</td>
                <td className={styles.td}>{appointment.NAME}</td>
                <td className={styles.td}>{appointment.MOBILE}</td>
                <td className={styles.td}>{appointment.EMAIL}</td>
                <td className={styles.td}>{appointment.DOCTOR}</td>
                <td className={styles.td}>{appointment.DESCRIPTION}</td>
              </tr>
            ))
          : null}
      </tbody>
    </table>
  );
}
