// reactFront/src/components/Doctor/Doctor.tsx
import { Link } from "react-router-dom";
import { Doctor } from "../../redux/DoctorReducer";
import styles from "./Doctor.module.css";

interface DoctorsProps {
  doctors: Doctor[];
  role: string;
  handleDoctorId: (id: number) => void;
}

export default function DoctorComponent({
  doctors,
  role,
  handleDoctorId,
}: DoctorsProps) {
  return (
    <section className={styles.doctorsSection}>
      <div className={styles.doctorsContainer}>
        <div className={styles.sectionHeading}>
          <p className="section-title">Doctors</p>
          <p className={styles.doctorsHeading}>Our Experienced Doctors</p>
        </div>
        <div className={`${styles.doctors} container`}>
          {doctors && doctors.length > 0
            ? doctors.map((doctor) => (
                <div className={styles.doctor} key={doctor.DOCTORID}>
                  {role === "3" ? (
                    <button
                      className={styles.deleteBtn}
                      onClick={() => handleDoctorId(doctor.DOCTORID)}
                    >
                      X
                    </button>
                  ) : null}

                  <Link to={`doctor-details/${doctor.DOCTORID}`}>
                    <div className={styles.doctorImg}>
                      {doctor.Files.length > 0 ? (
                        <img src={doctor.Files[0].URL} alt="" />
                      ) : null}
                    </div>
                  </Link>
                  <div className={styles.doctorInfo}>
                    <h5>{doctor.NAME}</h5>
                    <p>{doctor.DEPARTMENT}</p>
                    <ul className={styles.socialMediaList}>
                      <li className={styles.listIcons}>
                        <i className="fab fa-facebook-f"></i>
                      </li>
                      <li className={styles.listIcons}>
                        <i className="fab fa-twitter"></i>
                      </li>
                      <li className={styles.listIcons}>
                        <i className="fab fa-instagram"></i>
                      </li>
                    </ul>
                  </div>
                </div>
              ))
            : null}
        </div>
      </div>
    </section>
  );
}

// frontApp/src/components/doctor/doctor.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Doctor } from '../../services/doctor.service';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-doctor',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './doctor.component.html',
  styleUrl: './doctor.component.css',
})
export class DoctorComponent {
  @Input() doctors: Doctor[];
  @Input() roleId: number;
  @Output() doctorId: EventEmitter<number> = new EventEmitter();

  SendId(id: number) {
    this.doctorId.emit(id);
  }
}

<section class="doctors-section">
  <div class="doctors-container">
    <div class="section-heading">
      <p class="section-title">Doctors</p>
      <p class="doctors-heading">Our Experienced Doctors</p>
    </div>
    <div class="doctors container">
      @for(doctor of doctors; track doctor.DOCTORID){
      <div class="doctor" [routerLink]="['/doctordetails', doctor.DOCTORID]">
        @if(roleId && roleId === 3){
        <button class="delete-btn" (click)="SendId(doctor.DOCTORID)">X</button>
        }
        <div class="doctor-img">
          <img [src]="doctor.Files[0].URL" alt="" srcset="" />
        </div>
        <div class="doctor-info">
          <h5>{{ doctor.NAME }}</h5>
          <p>{{ doctor.DEPARTMENT }}</p>
          <ul class="social-media-list">
            <li class="list-icons">
              <a [href]="doctor.FACEBOOKLINK"
                ><i class="fab fa-facebook-f"></i
              ></a>
            </li>
            <li class="list-icons"><i class="fab fa-twitter"></i></li>
            <li class="list-icons"><i class="fab fa-instagram"></i></li>
          </ul>
        </div>
      </div>
      }
    </div>
  </div>
</section>
