// frontApp/src/components/info/info.component.ts
import { Component, Input } from '@angular/core';
import { Info } from '../../services/info.service';
import { CarouselComponent } from '../carousel/carousel.component';

@Component({
  selector: 'app-info',
  standalone: true,
  imports: [CarouselComponent],
  templateUrl: './info.component.html',
  styleUrl: './info.component.css',
})
export class InfoComponent {
  @Input() info: Info;
}

<section class="info-section">
  <div class="info">
    <div class="info-part">
      <div class="info-header">
        <p>Good Health Is The Root Of All Heppiness</p>
      </div>
      <div class="info-statistics">
        <div class="statistics-container">
          <div class="statistics">
            <p class="number">{{ info.DOCTORS }}</p>
            <p class="text">Expert Doctors</p>
          </div>
          <div class="statistics">
            <p class="number">{{ info.STAFF }}</p>
            <p class="text">Medical Staff</p>
          </div>
          <div class="statistics">
            <p class="number">{{ info.PATIENTS }}</p>
            <p class="text">Total Patients</p>
          </div>
        </div>
      </div>
    </div>
    <div class="info-carousel">
      <div class="carousel">
        <h1>Cardiology</h1>
        <img src="../../assets/carousel-1.jpg" alt="" class="carousel-img" />
      </div>
    </div>
  </div>
</section>

// reactFront/src/components/Info/Info.tsx
import styles from "./Info.module.css";
import img from "../../assets/carousel-1.jpg";
import { Information } from "../../redux/InfoReducer";

interface InfoProps {
  info: Information;
}

export default function Info({ info }: InfoProps) {
  return (
    <section className={styles.infoSection}>
      <div className={styles.info}>
        <div className={styles.infoPart}>
          <div className={styles.infoHeader}>
            <p>Good Health Is The Root Of All Heppiness</p>
          </div>
          <div className={styles.infoStatistics}>
            <div className={styles.statisticsContainer}>
              <div className={styles.statistics}>
                <p className={styles.number}>{info.DOCTORS}</p>
                <p className={styles.text}>Expert Doctors</p>
              </div>
              <div className={styles.statistics}>
                <p className={styles.number}>{info.STAFF}</p>
                <p className={styles.text}>Medical Staff</p>
              </div>
              <div className={styles.statistics}>
                <p className={styles.number}>{info.PATIENTS}</p>
                <p className={styles.text}>Total Patients</p>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.infoCarousel}>
          <div className={styles.carousel}>
            <h1>Cardiology</h1>
            <img src={img} alt="" className={styles.carouselImg} />
          </div>
        </div>
      </div>
    </section>
  );
}
