// reactFront/src/components/Feature/Feature.tsx
import Icon from "../Icon/Icon";
import styles from "./Feature.module.css";
import img from "../../assets/feature.jpg";
import { Feature } from "../../redux/FeatureReducer";

interface FeatureProps {
  feature: Feature;
}

export default function FeatureComponent({ feature }: FeatureProps) {
  return (
    <section className={styles.featuresSection}>
      <div className={styles.featuresContainer}>
        <div className={styles.featuresTexts}>
          <p className={styles.featuresTitle}>Features</p>
          <h1 className={styles.featuresHeading}>{feature.TITLE}</h1>
          <p className={styles.featuresInfo}>{feature.TEXT}</p>
          <div className={styles.featureIcons}>
            {feature.FEATUREITEMS.map((f) => (
              <div className={styles.iconItem} key={f.FEATUREITEMID}>
                <Icon
                  iconContainerSize={"iconContainerMd"}
                  cursorPointer={""}
                  icon={f.ICON}
                  iconSize={"iconMd"}
                />
                <div className={styles.iconTexts}>
                  <p className={styles.textOne}>{f.TEXTONE}</p>
                  <p className={styles.textTwo}>{f.TEXTTWO}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className={styles.imgContainer}>
          <img src={img} alt="" />
        </div>
      </div>
    </section>
  );
}

// frontApp/src/components/feature/feature.component.ts
import { Component, Input } from '@angular/core';
import { Feature } from '../../services/feature.service';
import { IconComponent } from '../icon/icon.component';

@Component({
  selector: 'app-feature',
  standalone: true,
  imports: [IconComponent],
  templateUrl: './feature.component.html',
  styleUrl: './feature.component.css',
})
export class FeatureComponent {
  @Input() feature: Feature;
}

<section class="features-section">
  <div class="features-container">
    <div class="features-texts">
      <p class="features-title">Features</p>
      <h1 class="features-heading">{{ feature.TITLE }}</h1>
      <p class="features-info">
        {{ feature.TEXT }}
      </p>
      <div class="feature-icons">
        @for(featureItem of feature.FEATUREITEMS; track
        featureItem.FEATUREITEMID){
        <div class="icon-item">
          <app-icon
            [icon]="featureItem.ICON"
            [iconContainerSize]="'icon-container-md'"
            [iconSize]="'icon-md'"
          ></app-icon>
          <div class="icon-texts">
            <p class="text-one">{{ featureItem.TEXTONE }}</p>
            <p class="text-two">{{ featureItem.TEXTTWO }}</p>
          </div>
        </div>
        }
      </div>
    </div>
    <div class="img-container">
      <img src="../../assets/feature.jpg" alt="" />
    </div>
  </div>
</section>
