// reactFront/src/components/HealthCare/HealthCare.tsx
import { Service } from "../../redux/HealthCareReducer";
import Icon from "../Icon/Icon";
import styles from "./HealthCare.module.css";

interface ServiceProps {
  services: Service[];
}

export default function HealthCare({ services }: ServiceProps) {
  return (
    <section className={styles.healthcareSection}>
      <div className={styles.titleContainer}>
        <p className="section-title">Services</p>
        <h1 className={styles.servicesHeading}>Health Care Solutions</h1>
      </div>

      <div className={`${styles.services} container`}>
        {services.map((service) => (
          <div className={styles.service} key={service.SERVICEID}>
            <Icon
              iconContainerSize={"iconContainerLg"}
              cursorPointer={""}
              icon={service.ICON}
              iconSize={"iconLg"}
            />
            <h4>{service.TITLE}</h4>
            <p>{service.TEXT}</p>
            <div className={styles.readMore}>
              <div className={styles.plusSign}>
                <i className="fa fa-plus"></i>
              </div>
              <p className={styles.readMoreText}>Read More</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

// frontApp/src/components/healthcare/healthcare.component.ts
import { Component, Input } from '@angular/core';
import { Service } from '../../services/service.service';
import { IconComponent } from '../icon/icon.component';

@Component({
  selector: 'app-healthcare',
  standalone: true,
  imports: [IconComponent],
  templateUrl: './healthcare.component.html',
  styleUrl: './healthcare.component.css',
})
export class HealthcareComponent {
  @Input() services: Service[];
}

<section class="healthcare-section">
  <div class="title-container">
    <p class="section-title">Services</p>
    <h1 class="services-heading">Health Care Solutions</h1>
  </div>
  <div class="services container">
    @if(services === undefined || services.length == 0){

    <h1>No services found</h1>

    }@else { @for(service of services; track service.SERVICEID) {

    <div class="service">
      <app-icon
        [icon]="service.ICON"
        [iconContainerSize]="'icon-container-lg'"
        [iconSize]="'icon-lg'"
      ></app-icon>
      <h4>{{ service.TITLE }}</h4>
      <p>{{ service.TEXT }}</p>
      <div class="read-more">
        <div class="plus-sign"><i class="fa fa-plus"></i></div>
        <p class="read-more-text">Read More</p>
      </div>
    </div>
    } }
  </div>
</section>
